version: 2

test: &test
  steps:
    - checkout
    - run:
        name: Run go mod
        command: |
          go mod download
          go mod vendor
    - run:
        name: Run vet
        command: go vet ./cmd/bookmarker/main.go
    - run:
        name: Run lint
        command: |
          go get -u github.com/golang/lint/golint
          golint -set_exit_status $(go list ./... | grep -v /vendor/)
    - run:
        name: Run staticcheck
        command: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          GO111MODULE=off staticcheck ./...

jobs:
  go-1.11-test:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/bookmarker
    <<: *test

workflows:
  version: 2
  build:
    jobs:
      - go-1.11-test
